backend/core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

backend/expense/urls.py
from django.urls import path

from backend.expense import views as v

app_name = 'expense'

urlpatterns = [
    path('', v.ExpenseListView.as_view(), name='expense_list'),
    path('create/', v.ExpenseCreateView.as_view(), name='expense_create'),
    path('<int:pk>/', v.ExpenseDetailView.as_view(), name='expense_detail'),
    path('<int:pk>/update/', v.expense_update, name='expense_update'),
    path('<int:pk>/delete/', v.expense_delete, name='expense_delete'),
]

backend/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('expense/', include('backend.expense.urls', namespace='expense')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

backend/expense/models.py
from django.urls import reverse_lazy
from django.db import models

from backend.core.models import TimeStampedModel

STATUS = (
    ('A', 'Aprovado'),
    ('c', 'Cancelado'),
)


class Expense(TimeStampedModel):
    title = models.CharField('título', max_length=5)
    value = models.DecimalField(
        'valor',
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
    )
    status = models.CharField(max_length=1, choices=STATUS, default='A')
    photo = models.ImageField(upload_to='', null=True, blank=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Despesa'
        verbose_name_plural = 'Despesas'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('expense:expense_detail', kwargs={'pk': self.pk})

backend/expense/forms.py
from django import forms

from .models import Expense


class ExpenseForm(forms.ModelForm):

    class Meta:
        model = Expense
        fields = (
            'title',
            'value',
            'status',
            'photo',
        )

backend/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

backend/expense/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy

from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from .models import Expense
from .forms import ExpenseForm


def expense_list(request):
    template_name = 'expense/expense_list.html'

    object_list = Expense.objects.all()

    context = {
        'object_list': object_list,
    }
    return render(request, template_name, context)


class ExpenseListView(ListView):
    template_name = 'expense/expense.html'
    model = Expense
    context_object_name = 'expenses'
    paginate_by = 3


def expense_detail(request, pk):
    template_name = 'expense/expense_detail.html'
    # instance = Expense.objects.get(pk=pk)
    instance = get_object_or_404(Expense, pk=pk)

    context = {
        'object': instance,
    }
    return render(request, template_name, context)


class ExpenseDetailView(DetailView):
    model = Expense


def expense_create(request):
    template_name = 'expense/expense_form.html'
    form = ExpenseForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('expense:expense_list')

        return redirect('expense:expense_create')

    context = {
        'form': form
    }
    return render(request, template_name, context)


class ExpenseCreateView(CreateView):
    model = Expense
    form_class = ExpenseForm
    success_url = reverse_lazy('expense:expense_list')


def expense_update(request, pk):
    template_name = 'expense/expense_form.html'
    instance = get_object_or_404(Expense, pk=pk)
    form = ExpenseForm(request.POST or None, request.FILES, instance=instance)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('expense:expense_list')

    context = {
        'object': instance,
        'form': form,
    }
    return render(request, template_name, context)


class ExpenseUpdateView(UpdateView):
    model = Expense
    form_class = ExpenseForm


def expense_delete(request, pk):
    instance = get_object_or_404(Expense, pk=pk)
    instance.delete()
    print('Deletado com sucesso.')
    return redirect('expense:expense_list')

backend/core/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <link rel="shortcut icon" href="https://alpinejs.dev/favicon.png">
  <title>Document</title>

  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>

<body>
  <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a
        href="/"
        class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
      >
        <svg
          class="bi me-2"
          width="40"
          height="32"
        >
          <use xlink:href="{% url 'core:index' %}"></use>
        </svg>
        <span class="fs-4">Despesas</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a
            href="{% url 'core:index' %}"
            class="nav-link active"
            aria-current="page"
          >Home</a></li>
        <li class="nav-item"><a
            href="{% url 'expense:expense_list' %}"
            class="nav-link"
          >Despesas</a></li>
      </ul>
    </header>

    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>
</body>

</html>

backend/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Index</h1>
{% endblock content %}

backend/expense/templates/expense/expense.html
{% extends "base.html" %}

{% block content %}
<h1>Lista de Despesas</h1>

<a
  href="{% url 'expense:expense_create' %}"
  class="btn btn-primary"
>Adicionar</a>

<table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Valor</th>
      <th>Status</th>
      <th>Comprovante</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for object in expenses %}
    <tr>
      <td>
        <a href="{{ object.get_absolute_url }}">{{ object }}</a>
      </td>
      <td>{{ object.value }}</td>
      <td>{{ object.get_status_display }}</td>
      <td>
        {% if object.photo %}
          <img src="{{ object.photo.url }}" alt="" height="100px">
        {% endif %}
      </td>
      <td>
        <!-- update -->
        <a
          href="{% url 'expense:expense_update' object.pk %}"
          class="mr-3"
        >
          <span>
            <i class="fa fa-pencil"></i>
          </span>
        </a>
        <!-- delete -->
        <a href="{% url 'expense:expense_delete' object.pk %}">
          <span>
            <i class="fa fa-trash text-danger"></i>
          </span>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

backend/expense/templates/expense/expense_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Despesa</h1>

<p>Título: {{ object }}</p>
<p>Valor: R$ {{ object.value }}</p>
<p>Status: {{ object.get_status_display }}</p>

{% if object.photo %}
<img
  src="{{ object.photo.url }}"
  alt=""
  height="300px"
>
{% endif %}
{% endblock content %}

backend/expense/templates/expense/expense_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<h1>Adicionar Despesa</h1>

<div>
  <form
    action="."
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %}

    <label for="">{{ form.title.label }}</label>
    {% render_field form.title class="form-control" %}
    {{ form.errors.title }}

    <label for="">{{ form.value.label }}</label>
    {% render_field form.value class="form-control" %}
    {{ form.errors.value }}

    <label for="">{{ form.status.label }}</label>
    {% render_field form.status class="form-control" %}
    {{ form.errors.status }}
    
    <label for="">{{ form.photo.label }}</label>
    {% render_field form.photo class="form-control" %}
    {{ form.errors.photo }}
    
    {% for error in form.non_field_errors %}
      <p class="text-danger">{{ error }}</p>
    {% endfor %}

    <button
      class="btn btn-primary mt-3"
      type="submit"
    >Salvar</button>
  </form>
</div>
{% endblock content %}